quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:task_user}
quarkus.datasource.password=${DB_PASSWORD:task_password}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/tasks}

quarkus.hibernate-orm.database.generation=update
